server:
  port: 8080
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true

plugins:
  lavasrc:
    sources:
      youtube: true
      soundcloud: true

logging:
  level:
    root: INFO