server:
  port: 8080
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true

plugins:
  lavasrc:
    providers:
      # When Apple Music returns metadata,
      # search YouTube Music for playable audio.
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"

    sources:
      applemusic: true
      spotify: false
      deezer: false
      yandexmusic: false
      flowerytts: false

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: INFO