services:

  lavalink:
    image: fredboat/lavalink:latest
    container_name: lavalink
    environment:
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    ports:
      - "8080:8080"

    restart: unless-stopped

  bot:
    build: .
    container_name: discord-bot
    depends_on:
      - lavalink

    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LAVALINK_URI=http://lavalink:8080
      - LAVALINK_PASSWORD=youshallnotpass

    restart: unless-stopped
