version: "3.9"

services:

  lavalink:
    image: fredboat/lavalink:4
    container_name: lavalink
    restart: unless-stopped

    environment:
      - _JAVA_OPTIONS=-Xmx1G

    env_file:
      - .env

    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
      - ./lavalink/plugins:/opt/Lavalink/plugins
      - ./storage/db:/app/storage/db

    ports:
      - "2333:2333"

    networks:
      - botnet


  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - lavalink

    networks:
      - botnet


networks:
  botnet:
    driver: bridge