server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "your_password_here"

    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      http: true

    bufferDurationMs: 400
    frameBufferDurationMs: 5000

    youtubePlaylistLoadLimit: 6
    soundcloudSearchEnabled: true