server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
  - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.1"
    version: 1.0.0

  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: false
      http: true

    bufferDurationMs: 400
    frameBufferDurationMs: 5000

    youtubePlaylistLoadLimit: 6
    soundcloudSearchEnabled: true